// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU8FNyAoI5JYqvxUSuzv938WiYTj8JFaM',
    appId: '1:65511654512:web:e92b181a7f56537c5a60b5',
    messagingSenderId: '65511654512',
    projectId: 'testing1-5c50b',
    authDomain: 'testing1-5c50b.firebaseapp.com',
    storageBucket: 'testing1-5c50b.firebasestorage.app',
    measurementId: 'G-3YTDR4NV5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA87XMur30LgyAbx8hxBFfYbmNR03Ct0Ug',
    appId: '1:65511654512:android:9b457165d6174af75a60b5',
    messagingSenderId: '65511654512',
    projectId: 'testing1-5c50b',
    storageBucket: 'testing1-5c50b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYSJTzT7XAW8dwyiIIIrmmHdXGf4_fkw',
    appId: '1:65511654512:ios:04542fb6660bea525a60b5',
    messagingSenderId: '65511654512',
    projectId: 'testing1-5c50b',
    storageBucket: 'testing1-5c50b.firebasestorage.app',
    iosBundleId: 'com.example.elmouaddibeExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYSJTzT7XAW8dwyiIIIrmmHdXGf4_fkw',
    appId: '1:65511654512:ios:04542fb6660bea525a60b5',
    messagingSenderId: '65511654512',
    projectId: 'testing1-5c50b',
    storageBucket: 'testing1-5c50b.firebasestorage.app',
    iosBundleId: 'com.example.elmouaddibeExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU8FNyAoI5JYqvxUSuzv938WiYTj8JFaM',
    appId: '1:65511654512:web:a7fe07d00bfe62195a60b5',
    messagingSenderId: '65511654512',
    projectId: 'testing1-5c50b',
    authDomain: 'testing1-5c50b.firebaseapp.com',
    storageBucket: 'testing1-5c50b.firebasestorage.app',
    measurementId: 'G-NPMEF2RC9W',
  );
}
